-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 01:34:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdzh
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdzh` ;

-- -----------------------------------------------------
-- Schema bdzh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdzh` DEFAULT CHARACTER SET utf8 ;
USE `bdzh` ;

-- -----------------------------------------------------
-- Table `bdzh`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdzh`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdzh`.`usuario` (
  `idUsu` INT NOT NULL AUTO_INCREMENT,
  `nomeUsu` VARCHAR(150) NOT NULL,
  `cpfUsu` VARCHAR(14) NULL,
  `dtNascimentoUsu` DATE NOT NULL,
  `telefoneUsu` VARCHAR(25) NULL,
  `emailUsu` VARCHAR(150) NOT NULL,
  `senhaUsu` VARCHAR(50) NOT NULL COMMENT 'Criptografia por MD5',
  `fotoUsu` VARCHAR(100) NULL,
  `perfilUsu` VARCHAR(45) NULL DEFAULT 'Cliente' COMMENT 'Administrador\nFuncionário\nCliente',
  `situacaoUsu` CHAR(7) NULL DEFAULT 'Ativo' COMMENT 'Ativo\nInativo',
  `assinaturaUsu` VARCHAR(50) NULL COMMENT 'Mensal\nSemestral\nAnual',
  `acessoUsu` VARCHAR(2) NULL DEFAULT '1' COMMENT '1\n2\n3',
  PRIMARY KEY (`idUsu`),
  UNIQUE INDEX `cpfUsu_UNIQUE` (`cpfUsu` ASC) ,
  UNIQUE INDEX `emailUsu_UNIQUE` (`emailUsu` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdzh`.`pacote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdzh`.`pacote` ;

CREATE TABLE IF NOT EXISTS `bdzh`.`pacote` (
  `idPac` INT NOT NULL AUTO_INCREMENT,
  `nomePac` VARCHAR(100) NOT NULL,
  `valorVendaPac` DECIMAL(13,2) NOT NULL DEFAULT 0,
  `imagemPac` VARCHAR(100) NULL,
  `codigoPac` INT NOT NULL,
  `situacaoPac` VARCHAR(15) NOT NULL DEFAULT 'Disponível' COMMENT 'Disponível\nIndisponível',
  `descricaoPac` TEXT NULL,
  `tituloPac` VARCHAR(30) NULL,
  `estrelaPac` VARCHAR(100) NULL,
  `comentarioPac` TEXT NULL,
  PRIMARY KEY (`idPac`),
  UNIQUE INDEX `codigoPac_UNIQUE` (`codigoPac` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdzh`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdzh`.`pedido` ;

CREATE TABLE IF NOT EXISTS `bdzh`.`pedido` (
  `idPed` INT NOT NULL AUTO_INCREMENT,
  `dtHoraPed` DATETIME NOT NULL,
  `valorTotalPed` DECIMAL(13,2) NOT NULL DEFAULT 0,
  `situacaoPed` VARCHAR(10) NULL DEFAULT 'Aberto' COMMENT 'Aberto\nFinalizado\nCancelar',
  `formaPagamentoPed` VARCHAR(45) NOT NULL DEFAULT 'Não definido' COMMENT 'Não definido\nPIX\nCartão de Crédito\nCartão de Débito\nBoleto\nMoeda Digital',
  `pedido_idUsu` INT NOT NULL,
  `pacote_idPac` INT NOT NULL,
  PRIMARY KEY (`idPed`, `pacote_idPac`),
  INDEX `fk_table2_pedido_idx` (`pedido_idUsu` ASC) ,
  INDEX `fk_pedido_pacote1_idx` (`pacote_idPac` ASC) ,
  CONSTRAINT `fk_table2_pedido`
    FOREIGN KEY (`pedido_idUsu`)
    REFERENCES `bdzh`.`usuario` (`idUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pacote1`
    FOREIGN KEY (`pacote_idPac`)
    REFERENCES `bdzh`.`pacote` (`idPac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdzh`.`treino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdzh`.`treino` ;

CREATE TABLE IF NOT EXISTS `bdzh`.`treino` (
  `idTre` INT NOT NULL AUTO_INCREMENT,
  `statusTre` VARCHAR(20) NOT NULL COMMENT 'Disponível\nIndisponível\n',
  `descricaoTre` VARCHAR(20) NULL,
  `videoTre` VARCHAR(400) NULL,
  `tituloTre` VARCHAR(30) NULL,
  `tipoTre` VARCHAR(20) NULL COMMENT 'Emagrecer\nFortalecer\nGanhar Massa',
  PRIMARY KEY (`idTre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdzh`.`pacote_has_treino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdzh`.`pacote_has_treino` ;

CREATE TABLE IF NOT EXISTS `bdzh`.`pacote_has_treino` (
  `pacote_idPac` INT NOT NULL,
  `treino_idTre` INT NOT NULL,
  PRIMARY KEY (`pacote_idPac`, `treino_idTre`),
  INDEX `fk_pacote_has_treino_treino1_idx` (`treino_idTre` ASC) ,
  INDEX `fk_pacote_has_treino_pacote1_idx` (`pacote_idPac` ASC) ,
  CONSTRAINT `fk_pacote_has_treino_pacote1`
    FOREIGN KEY (`pacote_idPac`)
    REFERENCES `bdzh`.`pacote` (`idPac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pacote_has_treino_treino1`
    FOREIGN KEY (`treino_idTre`)
    REFERENCES `bdzh`.`treino` (`idTre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `usuario` (`idUsu`, `nomeUsu`, `emailUsu`, `cpfUsu`, `telefoneUsu`, `dtNascimentoUsu`, `senhaUsu`, `perfilUsu`, `situacaoUsu`, `fotoUsu`) VALUES (NULL, 'Administrador', 'adm@gmail.com', '123.456.789-10', '(61) 9999-9999', '2024-05-01', MD5('123'), 'Administrador', 'Ativo', NULL);

INSERT INTO `usuario` (`idUsu`, `nomeUsu`, `emailUsu`, `cpfUsu`, `telefoneUsu`, `dtNascimentoUsu`, `senhaUsu`, `perfilUsu`, `situacaoUsu`, `fotoUsu`) VALUES (NULL, 'Funcionário', 'funcionario@gmail.com', '999.999.999-99', '(61) 1234-5678', '2024-05-06', MD5('123'), 'Funcionário', 'Ativo', NULL);


INSERT INTO `pacote` (`idPac`, `nomePac`, `valorVendaPac`, `imagemPac`, `codigoPac`, `situacaoPac`, `descricaoPac`, `tituloPac`, `estrelaPac`, `comentarioPac`) VALUES (NULL, 'Mensal', '30.00', 'zBronze.png', '1', 'Disponível', 'Pacote mensal', 'Mensal', NULL, NULL), 
(NULL, 'Semestral', '165.00', 'zPrata.png', '2', 'Disponível', 'Pacote Semestral', 'Semestral', NULL, NULL), 
(NULL, 'Anual', '325.00', 'zDourado.png', '3', 'Disponível', 'Pacote Anual', 'Anual', NULL, NULL);


INSERT INTO `treino` (`idTre`, `statusTre`, `descricaoTre`, `videoTre`, `tituloTre`, `tipoTre`) VALUES (NULL, 'Disponível', 'perda de peso', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/cmzKlw1IVAg?si=RimFmKBigF3vSTev\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Circuito dinâmico', 'Emagrecer'),
 (NULL, 'Disponível', '15 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/q_e_m6j0RN0?si=6QhikIDPpIMQZoKT\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Queimar gordura', 'Emagrecer'), 
 (NULL, 'Disponível', 'secar barriga', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DtXZy7yVt-g?si=k-DZX6_MUqbNSa3C\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Cárdio Abdominal', 'Emagrecer'), 
 (NULL, 'Disponível', 'Emagrecer', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/UheajlsZ72E?si=NPVKxc2_TzOU_Dpw\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Workouts', 'Emagrecer'),
 (NULL, 'Disponível', 'Completo', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/q7dV98L17jQ?si=_iJwxY_ZpeYnPoZm\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino tonificador', 'Emagrecer'), 
 (NULL, 'Disponível', ' Fit', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DqNTAwE4REE?si=rDg_F-9GkMOc67mV\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Playdance', 'Emagrecer'), 
 (NULL, 'Disponível', '5 exercícios', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/umLrxuDkmjM?si=eeK6-BCNQnxKlSfR\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Pilates', 'Emagrecer'),
 (NULL, 'Disponível', 'Full body', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/VG1W5qxLFNU?si=0TFJ-erp7m1banUH\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino emagrecer', 'Emagrecer'), 
 (NULL, 'Disponível', '10 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/sXXELyyjZWk?si=-DaktbrCRheDVHSy\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Power hit', 'Emagrecer'), 
 (NULL, 'Disponível', 'Secar barriga', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/cvm89a_cHKA?si=yVte1cg7IOmJkAGU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Fit dance', 'Emagrecer'), 
 (NULL, 'Disponível', '15 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/J212vz33gU4?si=JDkWiFTBoPFl9DFM\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'HIT Workout', 'Emagrecer'), 
 (NULL, 'Disponível', 'Workout', '<iframe width="560" height="315" src="https://www.youtube.com/embed/rosIwQajcaA?si=pYaadvi9FIOhFfD0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>', 'Cardio Hit', 'Emagrecer');


INSERT INTO `treino` (`idTre`, `statusTre`, `descricaoTre`, `videoTre`, `tituloTre`, `tipoTre`) VALUES (NULL, 'Disponível', '30 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/9FBIaqr7TjQ?si=WjP0x8RqVnQtPylz\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Strength Workout', 'Fortalecer'),
(NULL, 'Disponível', '20 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/VjGOiFr5oAk?si=9DdxlkckLtC37Upx\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de glúteos', 'Fortalecer'),
(NULL, 'Disponível', 'e costas', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/I2C5g8u8t0o?si=ZX6jWKgEgIesZy-s\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de Braços', 'Fortalecer'),
(NULL, 'Disponível', 'Foco em costas', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/1tHZ-hUH2P8?si=1zifwsYDui9BbY6V\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'PULL WORKOUT', 'Fortalecer'),
(NULL, 'Disponível', 'Abdômen', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/GoiZK4AsizM?si=znhUGKCER06Ggj5O\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Fortalecer', 'Fortalecer'),
(NULL, 'Disponível', '10 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/tznOr5ILEQs?si=d7dbSL_QyvYvvbMm\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Peitoral', 'Fortalecer'),
(NULL, 'Disponível', 'e Glúteos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/igtL2m8oH2I?si=oN7JndiodNgNMNce\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de Pernas', 'Fortalecer'),
(NULL, 'Disponível', 'e Bíceps', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/DT4QjwTaf5Q?si=7woGq3CbK1T0yXA8\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Costas', 'Fortalecer'),
(NULL, 'Disponível', 'Full body', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/qPtnAnH5pNc?si=pD_xdb3yXaubfdqk\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Estabilidade', 'Fortalecer'),
(NULL, 'Disponível', 'com Kettlebells', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/UxfX7Z4am1Q?si=1caqC5E5w8DAFAcW\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de Corpo Inteiro', 'Fortalecer'),
(NULL, 'Disponível', 'Força e Estabilidade', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Eml2xnoLpYE?si=WyijfgK2yQYpYYe9\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Body Yoga', 'Fortalecer'),
(NULL, 'Disponível', '15 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/eu7z5tt3PRk?si=Xk-Qs9csBcUHEvwq\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino Funcional', 'Fortalecer');


INSERT INTO `treino` (`idTre`, `statusTre`, `descricaoTre`, `videoTre`, `tituloTre`, `tipoTre`) VALUES (NULL, 'Disponível', 'workout', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0A3EgOztptQ?si=y65Ex-cAcpQo_5AD\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Full body', 'Ganhar Massa'),
(NULL, 'Disponível', 'em 14 minutos', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/71op1DQ2gyo?si=IKOnoEZoRSvZs4Nl\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de Hipertrofia', 'Ganhar Massa'), 
(NULL, 'Disponível', 'abdômen', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/TqXwI1MWZks?si=r4k0loN-hkubrwbp\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Exercicios de', 'Ganhar Massa'),
(NULL, 'Disponível', '5x na semana', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/eTxO5ZMxcsc?si=vCIHOyG6_6qX3bAO\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Full Body', 'Ganhar Massa'), 
(NULL, 'Disponível', 'halteres', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/vxk87gdCCjQ?si=DsgGQXHMRFv5G5Ar\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Exercícios com', 'Ganhar Massa'),
(NULL, 'Disponível', 'hipertrofia', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/H6mRkx1x77k?si=icVtA1uuOoT4myUo\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de perna', 'Ganhar Massa'), 
(NULL, 'Disponível', 'com corda', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Nj6kgsxaUGg?si=9YMS4kOF0WSJRlwU\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Bíceps e Tríceps', 'Ganhar Massa'), 
(NULL, 'Disponível', 'completo', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/vCNONR6unm8?si=POTqr4m8llob39HK\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de peito', 'Ganhar Massa'), 
(NULL, 'Disponível', 'abdômen', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/QdIutxfm_hU?si=S3jRfr_B1Pb_uDQq\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Exercícios de ', 'Ganhar Massa'), 
(NULL, 'Disponível', 'em hipertrofia', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/xc4OtzAnVMI?si=JPJ1ive3ql3VHvry\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino focado', 'Ganhar Massa'), 
(NULL, 'Disponível', '5 exercícios', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/oGFmeKD5z-E?si=gDYKhvARFh_0FuQi\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Treino de Glúteos', 'Ganhar Massa'),
(NULL, 'Disponível', 'calistenia', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/G1pjiMhGP5w?si=l7kMU6oNwn0eBrax\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>', 'Exercícios de', 'Ganhar Massa');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;







